definitions:
  api.ProductDtoIn:
    properties:
      description:
        type: string
      name:
        type: string
    required:
    - description
    - name
    type: object
  api.ProductDtoOut:
    properties:
      description:
        type: string
      id:
        type: string
      name:
        type: string
    required:
    - description
    - id
    - name
    type: object
info:
  contact: {}
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Go Web API
  version: "0.1"
paths:
  /product:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/api.ProductDtoOut'
            type: array
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Error
          schema:
            type: string
      tags:
      - Product
    post:
      consumes:
      - application/json
      parameters:
      - description: Product data
        in: body
        name: productDTO
        required: true
        schema:
          $ref: '#/definitions/api.ProductDtoIn'
      produces:
      - application/json
      responses:
        "201":
          description: OK
          schema:
            $ref: '#/definitions/api.ProductDtoOut'
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Error
          schema:
            type: string
      tags:
      - Product
  /product/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Product UUID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Error
          schema:
            type: string
      tags:
      - Product
    get:
      parameters:
      - description: Product UUID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.ProductDtoOut'
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Error
          schema:
            type: string
      tags:
      - Product
    put:
      consumes:
      - application/json
      parameters:
      - description: Product UUID
        in: path
        name: id
        required: true
        type: string
      - description: Product data
        in: body
        name: productData
        required: true
        schema:
          $ref: '#/definitions/api.ProductDtoIn'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.ProductDtoOut'
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
        "500":
          description: Internal Error
          schema:
            type: string
      tags:
      - Product
swagger: "2.0"
